!obj:pylearn2.train.Train {
    dataset: &train !obj:pylearn2.datasets.dense_design_matrix.DenseDesignMatrix {
        X: !pkl: '/home/marc/git/MI10_adversarial_training/training_test/MLP3/my_X.pkl',
        y: !pkl: '/home/marc/git/MI10_adversarial_training/training_test/MLP3/my_y.pkl',
        y_labels: 3,
    },
    model: !obj:pylearn2.models.mlp.MLP {
        layers: [ !obj:pylearn2.models.mlp.RectifiedLinear {
                     layer_name: 'h0',
                     dim: 3,
                     sparse_init: 2,
                 }, !obj:pylearn2.models.mlp.Softmax {
                     layer_name: 'y',
                     n_classes: 3,
                     irange: 0.
                 }
                ],
        nvis: 3,
    },
    algorithm: !obj:pylearn2.training_algorithms.sgd.SGD {
        batch_size: 1,
        learning_rate: .01,
        # learning_rule: !obj:pylearn2.training_algorithms.learning_rule.Momentum {
        #     init_momentum: .5
        # },
        monitoring_dataset: {
            'train' : *train,
            'valid' : *train,
            'test' : *train
        },
        termination_criterion: !obj:pylearn2.termination_criteria.And {
            criteria: [
                !obj:pylearn2.termination_criteria.MonitorBased {
                    channel_name: "valid_y_misclass",
                    prop_decrease: 0.,
                    N: 100
                },
                !obj:pylearn2.termination_criteria.EpochCounter {
                    max_epochs: 1500
                }
            ]
        },
        # cost: !obj:costAdv.AdversarialCost {
        #     learning_eps: %(learning_eps)f
        # }
    },
    extensions: [
           !obj:pylearn2.train_extensions.best_params.MonitorBasedSaveBest {
             channel_name: 'valid_y_misclass',
             save_path: "%(save_path)s/mem/mlp_1_%(learning_eps)s.pkl",
        },
        #  !obj:pylearn2.training_algorithms.learning_rule.MomentumAdjustor {
        #     start: 1,
        #     saturate: 10,
        #     final_momentum: .99
        # }
    ]
    # save_path: "%(save_path)s/mlp%(learning_eps)s.pkl",
    # save_freq : 20
}

# python -c "from pylearn2.utils import serial; \
#            train_obj = serial.load_train_file('mlp.yaml'); \
#            train_obj.main_loop()"



